//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum CommonResponseExitCodes { 
	/** api exited successfully */
	Successful = 0, 
	/** unhandled exception occurred */
	Error = 1, 
	/** access denied due to missing valid authentication */
	InvalidAuth = 2
}
