//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CommonResponseExitCodes } from './CommonResponseExitCodes';

export interface ICommonResponse
{
	/**
	* 0 - ok
	*             1 - error ( see ErrorMsg and stackTrace)
	*             2 - invalid auth
	*/
	exitCode: CommonResponseExitCodes;
	errorMsg: string;
	stackTrace: string;
}
