//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IRecordBase } from './IRecordBase';

export interface IIRecord extends IRecordBase
{
	id: number;
	/** user timestamp ( serveR:UTC js:LOCAL ) */
	update_timestamp?: Date;
}
