//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ISampleTable
{
	id: number;
	/** create timestamp ( UTC ) */
	create_timestamp: any;
	/** user timestamp ( UTC ) */
	user_timestamp: any;
}
