//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ISampleTable
{
	id: number;
	/** create timestamp ( server:UTC js:LOCAL ) */
	create_timestamp: Date;
	/** user timestamp ( serveR:UTC js:LOCAL ) */
	user_timestamp: Date;
}
