//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ICommonRequest } from './ICommonRequest';

export interface ITemplatedRequest<T> extends ICommonRequest
{
	data: T;
}
